In [12]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [13]:
df=pd.read_csv("spam.csv",encoding="latin-1")
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [14]:
df.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='str')

In [15]:
df.shape

(5572, 5)

In [16]:
df=df[["v1","v2"]]
df.columns=["label","message"]
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [17]:
df=df.dropna()

In [18]:
df.duplicated().sum()

np.int64(403)

In [19]:
df=df.drop_duplicates()

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df["label"]=df["label"].map({"ham":0,"spam":1})

In [24]:
df["label"].value_counts()

label
0    4516
1     653
Name: count, dtype: int64

In [25]:
x=df["message"]
y=df["label"]

In [26]:
x

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: message, Length: 5169, dtype: str

In [27]:
y

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: label, Length: 5169, dtype: int64

In [28]:
x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.2,random_state=42,stratify=y)

In [29]:
vactorizer=TfidfVectorizer(lowercase=True,stop_words="english")
x_train=vactorizer.fit_transform(x_train)
x_test=vactorizer.transform(x_test)

In [30]:
model=MultinomialNB()
model.fit(x_train,y_train)

MultinomialNB()

In [31]:
y_pred=model.predict(x_test)

In [33]:
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)

0.9661508704061895

In [34]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[902   1]
 [ 34  97]]

In [36]:
cr=classification_report(y_test,y_pred,target_names=["ham","spam"])
print(cr)

              precision    recall  f1-score   support

         ham       0.96      1.00      0.98       903
        spam       0.99      0.74      0.85       131

    accuracy                           0.97      1034
   macro avg       0.98      0.87      0.91      1034
weighted avg       0.97      0.97      0.96      1034

In [39]:
always_ham=np.zeros(len(y_test))
baseline_accuracy=accuracy_score(
    y_test,
    always_ham)

print(baseline_accuracy)
print(accuracy)

0.8733075435203095
0.9661508704061895

In [41]:
always_ham=np.zeros(len(y_test))
baseline_accuracy=accuracy_score(y_test,always_ham)
print(baseline_accuracy)

0.8733075435203095

In [51]:
my_messages=[
    "Congratulations! You won a free iPhone. Claim now!",
    "Hey, are you coming to college today?",
    "URGENT! You have won 50000 dollars. Call now!",
    "Can you send me the assignment?",
    "Get a free reward by clicking this link"
]

In [53]:
my_msg=vactorizer.transform(my_messages)
predictions=model.predict(my_message)

In [54]:
for message,prediction in zip(my_messages,predictions):
    if prediction==1:
        result="spam"
    else:
        result="ham"
    print(message)
    print(result)
    print()

Congratulations! You won a free iPhone. Claim now!
spam

Hey, are you coming to college today?
ham

URGENT! You have won 50000 dollars. Call now!
ham

Can you send me the assignment?
ham

Get a free reward by clicking this link
ham